env:
  node: true
  browser: false
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - import
settings:
  import/resolver:
    typescript: true
    node: true
rules:
  no-console: 'warn'
  prettier/prettier: 'error'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/no-empty-function': 'off'
  '@typescript-eslint/no-unnecessary-type-constraint': 'off'
  '@typescript-eslint/no-unused-vars': 'error'
  import/no-unresolved: 'warn'
